version: "3"

services:
  db:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123"
      PGDATA: /data/postgres
      POSTGRES_DB: carentals
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  # api:
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #     target: dev
  #   volumes:
  #     - .:/opt/app/api