// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: service_car_rentals.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CarRentalsClient is the client API for CarRentals service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CarRentalsClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error)
}

type carRentalsClient struct {
	cc grpc.ClientConnInterface
}

func NewCarRentalsClient(cc grpc.ClientConnInterface) CarRentalsClient {
	return &carRentalsClient{cc}
}

func (c *carRentalsClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/pb.CarRentals/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *carRentalsClient) LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error) {
	out := new(LoginUserResponse)
	err := c.cc.Invoke(ctx, "/pb.CarRentals/LoginUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CarRentalsServer is the server API for CarRentals service.
// All implementations must embed UnimplementedCarRentalsServer
// for forward compatibility
type CarRentalsServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error)
	mustEmbedUnimplementedCarRentalsServer()
}

// UnimplementedCarRentalsServer must be embedded to have forward compatible implementations.
type UnimplementedCarRentalsServer struct {
}

func (UnimplementedCarRentalsServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedCarRentalsServer) LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginUser not implemented")
}
func (UnimplementedCarRentalsServer) mustEmbedUnimplementedCarRentalsServer() {}

// UnsafeCarRentalsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CarRentalsServer will
// result in compilation errors.
type UnsafeCarRentalsServer interface {
	mustEmbedUnimplementedCarRentalsServer()
}

func RegisterCarRentalsServer(s grpc.ServiceRegistrar, srv CarRentalsServer) {
	s.RegisterService(&CarRentals_ServiceDesc, srv)
}

func _CarRentals_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarRentalsServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CarRentals/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarRentalsServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CarRentals_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarRentalsServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.CarRentals/LoginUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarRentalsServer).LoginUser(ctx, req.(*LoginUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CarRentals_ServiceDesc is the grpc.ServiceDesc for CarRentals service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CarRentals_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CarRentals",
	HandlerType: (*CarRentalsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _CarRentals_CreateUser_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _CarRentals_LoginUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_car_rentals.proto",
}
